language: ruby
cache: bundler

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - rbx-2
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - thomas.dmytryk@supinfo.com
script: bundle exec rspec spec