language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - jruby-19mode
  - rbx-19mode
  - 2.0.0
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - thomas.dmytryk@supinfo.com
script: bundle exec rspec spec